AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Storage Facilities
Globals:
  Function:
    Timeout: 30
    Runtime: python3.9
Resources:
  #########################################
  # API Gateway
  #########################################
  StorageApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: StorageApi
      StageName: dev
      Cors: 
        AllowOrigin: "'*'"
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:eu-west-1:476114118819:userpool/eu-west-1_i7fFDRkBC
            Identity:
              Headers:
                - Authorization

  #########################################
  # DynamoDB Tables
  #########################################
  StorageTypesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: StorageTypesTable
      AttributeDefinitions:
        - AttributeName: typeId
          AttributeType: S
      KeySchema:
        - AttributeName: typeId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  StorageUnitsTableV2:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: StorageUnitsTableV2
      AttributeDefinitions:
        - AttributeName: unitId
          AttributeType: S
        # - AttributeName: typeId
        #   AttributeType: S
      KeySchema:
        - AttributeName: unitId
          KeyType: HASH
      #   - AttributeName: typeId
      #     KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  UserProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserProfilesTable
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  BookingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BookingsTable
      AttributeDefinitions:
        - AttributeName: bookingId
          AttributeType: S
        - AttributeName: customerId
          AttributeType: S
      KeySchema:
        - AttributeName: bookingId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: CustomerIndex
          KeySchema:
            - AttributeName: customerId
              KeyType: HASH
          Projection:
            ProjectionType: ALL


  #########################################
  # Storage Function Role
  #########################################      
  StorageNookFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:BatchWriteItem
                Resource:
                  - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/StorageTypesTable
                  - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/StorageUnitsTableV2
                  - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/UserProfilesTable
                  - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/BookingsTable
                  - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/BookingsTable/index/CustomerIndex

  #########################################
  # Create Storage Type Function
  #########################################                
  CreateStorageTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create-storage-type-function
      CodeUri: src/api/storage_types/
      Handler: create_storage_type.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
          - StorageNookFunctionRole
          - Arn
      Environment:
        Variables:
          TABLE_NAME: StorageTypesTable
      Events:
        CreateStorageType:
          Type: Api
          Properties:
            RestApiId:
              Ref: StorageApi
            Path: /storage-types
            Method: post
            Auth:
              Authorizer: CognitoAuthorizer

  #########################################
  # Create Storage Unit Function
  #########################################
  CreateStorageUnitFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create-storage-unit-function
      CodeUri: src/api/storage_units/
      Handler: create_storage_unit.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
          - StorageNookFunctionRole
          - Arn
      Environment:
        Variables:
          TABLE_NAME: StorageUnitsTableV2
          STORAGE_TYPES_TABLE: StorageTypesTable
      Events:
        CreateStorageUnit:
          Type: Api
          Properties:
            RestApiId:
              Ref: StorageApi
            Path: /storage-types/{typeId}/units
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  #########################################
  # Get Storage Units Function
  #########################################
  GetStorageUnitsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-storage-units-function
      CodeUri: src/api/storage_units/
      Handler: get_storage_units.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
          - StorageNookFunctionRole
          - Arn
      Environment:
        Variables:
          TABLE_NAME: StorageUnitsTableV2
      Events:
        GetStorageUnits:
          Type: Api
          Properties:
            RestApiId:
              Ref: StorageApi
            Path: /units
            Method: GET

  #########################################
  # Update Unit Function
  #########################################
  UpdateUnitFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: update-unit-function
      CodeUri: src/api/storage_units/
      Handler: update_unit.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
          - StorageNookFunctionRole
          - Arn
      Environment:
        Variables:
          TABLE_NAME: StorageUnitsTableV2
      Events:
        UpdateUnit:
          Type: Api
          Properties:
            RestApiId:
              Ref: StorageApi
            Path: /units/{unitId}
            Method: PUT
            Auth:
              Authorizer: CognitoAuthorizer

  #########################################
  # Delete Unit Function
  #########################################
  DeleteUnitFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: delete-unit-function
      CodeUri: src/api/storage_units/
      Handler: delete_unit.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
          - StorageNookFunctionRole
          - Arn
      Environment:
        Variables:
          TABLE_NAME: StorageUnitsTableV2
      Events:
        DeleteUnit:
          Type: Api
          Properties:
            RestApiId:
              Ref: StorageApi
            Path: /units/{unitId}
            Method: DELETE
            Auth:
              Authorizer: CognitoAuthorizer
    Metadata:
      SamResourceId: DeleteUnitFunction

  #########################################
  # Create or Update Profile Function
  #########################################                
  CreateOrUpdateProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create-or-update-profile-function
      CodeUri: src/api/profiles/
      Handler: create_or_update_profile.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
          - StorageNookFunctionRole
          - Arn
      Environment:
        Variables:
          TABLE_NAME: UserProfilesTable
      Events:
        CreateOrUpdateProfile:
          Type: Api
          Properties:
            RestApiId:
              Ref: StorageApi
            Path: user/profile
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer


  #########################################
  # Get Profile Function
  #########################################                
  GetProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-profile-function
      CodeUri: src/api/profiles/
      Handler: get_profile.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
          - StorageNookFunctionRole
          - Arn
      Environment:
        Variables:
          TABLE_NAME: UserProfilesTable
      Events:
        GetProfile:
          Type: Api
          Properties:
            RestApiId: 
              Ref: StorageApi
            Path: user/profile
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  #########################################
  # Create Customer Booking Function
  #########################################                
  CreateBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create-booking-function
      CodeUri: src/api/bookings/
      Handler: create_booking.lambda_handler
      Role:
        Fn::GetAtt:
          - StorageNookFunctionRole
          - Arn
      Environment:
        Variables:
          TABLE_NAME: BookingsTable
          UNITS_TABLE: StorageUnitsTableV2
      Events:
        CreateBooking:
          Type: Api
          Properties:
            RestApiId: 
              Ref: StorageApi
            Path: /bookings
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  #########################################
  # Get Customer Bookings Function
  #########################################
  GetCustomerBookingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-customer-bookings-function
      CodeUri: src/api/bookings/
      Handler: get_customer_bookings.lambda_handler
      Role: 
        Fn::GetAtt:
          - StorageNookFunctionRole
          - Arn
      Environment:
        Variables:
          TABLE_NAME: BookingsTable
          UNITS_TABLE: StorageUnitsTableV2
      Events:
        GetCustomerBookings:
          Type: Api
          Properties:
            RestApiId: 
              Ref: StorageApi
            Path: /customers/{customerId}/bookings
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  #########################################
  # Update Booking Function
  #########################################
  UpdateBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: update-booking-function
      CodeUri: src/api/bookings/
      Handler: update_booking.lambda_handler
      Role: 
        Fn::GetAtt: 
          - StorageNookFunctionRole
          - Arn
      Environment:
        Variables:
          TABLE_NAME: BookingsTable
          UNITS_TABLE: StorageUnitsTableV2
      Events:
        UpdateBooking:
          Type: Api
          Properties:
            RestApiId:
              Ref: StorageApi
            Path: /bookings/{bookingId}
            Method: PUT
            Auth:
              Authorizer: CognitoAuthorizer

  #########################################
  # Cancel Booking Function
  #########################################
  CancelBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cancel-booking-function
      CodeUri: src/api/bookings/
      Handler: cancel_booking.lambda_handler
      Role: 
        Fn::GetAtt:
          - StorageNookFunctionRole
          - Arn
      Environment:
        Variables:
          TABLE_NAME: BookingsTable
          UNITS_TABLE: StorageUnitsTableV2
      Events:
        CancelBooking:
          Type: Api
          Properties:
            RestApiId:
              Ref: StorageApi
            Path: /bookings/{bookingId}/cancel
            Method: PUT
            Auth:
              Authorizer: CognitoAuthorizer

  #########################################
  # Process Payment Function
  #########################################
  ProcessPaymentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: process-payment-function
      CodeUri: src/api/bookings/
      Handler: process_payment.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
          - StorageNookFunctionRole
          - Arn
      Environment:
        Variables:
          BOOKINGS_TABLE: BookingsTable
          PROFILES_TABLE: UserProfilesTable
      Events:
        SimulatePayment:
          Type: Api
          Properties:
            RestApiId:
              Ref: StorageApi
            Path: /bookings/{bookingId}/pay
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  #########################################
  # Manage Payment Method Function
  #########################################
  ManagePaymentMethodsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: manage-payment-methods-function
      CodeUri: src/api/profiles/
      Handler: manage_payment_methods.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
          - StorageNookFunctionRole
          - Arn
      Environment:
        Variables:
          TABLE_NAME: UserProfilesTable
      Events:
        ManagePaymentMethods:
          Type: Api
          Properties:
            RestApiId:
              Ref: StorageApi
            Path: /users/payment-methods
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer



#########################################
# Outputs
#########################################
Outputs:
  StorageApiId:
    Description: ID of the Storage API Gateway
    Value:
        Ref: StorageApi
    Export:
      Name: StorageApiId
  ApiEndpoint:
    Description: URL for the Storage API Gateway
    Value:
      Fn::Sub: https://${StorageApi}.execute-api.${AWS::Region}.amazonaws.com/dev/
    Export:
      Name: StorageApiEndpoint
  StorageTypesTableName:
    Description: Name of the DynamoDB table for storage types
    Value:
      Ref: StorageTypesTable
    Export:
      Name: StorageTypesTableName
  StorageUnitsTableV2Name:
    Description: Name of the DynamoDB table for storage units
    Value:
      Ref: StorageUnitsTableV2
    Export:
      Name: StorageUnitsTableV2Name
  StorageNookFunctionRoleArn:
    Description: ARN of the IAM role used by Lambda functions
    Value:
      Fn::GetAtt:
        - StorageNookFunctionRole
        - Arn
    Export:
      Name: StorageNookFunctionRoleArn
  BookingsTableName:
    Description: Name of the DynamoDB table for bookings
    Value: 
      Ref: BookingsTable
    Export:
      Name: BookingsTableName
