version = 0.1
[default.deploy.parameters]
stack_name = "storage-nook-userpool-stack"
resolve_s3 = true
s3_prefix = "storage-nook-userpool-stack"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "DomainPrefix=\"storagenookapp\""
